name: OnimaGames
author: Jestiz
main: net.onima.onimagames.OnimaGames
version: 1.0
description: Games
depend: [OnimaAPI, OnimaFaction]

commands:
  game:
    description: Commande principale pour les events.
    permission: onimagames.game.command
  koth:
    description: Commande principale pour les KoTH.
    permission: onimagames.koth.command
  conquest:
    description: Command principale pour les Conquest.
    permission: onimagames.conquest.command
  citadel:
    description: Command principale pour les Citadel.
    permission: onimagames.citadel.command
  dtc:
    description: Command principale pour les DTC.
    permission: onimagames.dtc.command
  dragon:
    description: Command principale pour les events Dragon.
    permission: onimagames.dragon.command